# Generated by Django 2.0.3 on 2018-03-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='page_id',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='result_url',
            field=models.CharField(default='', max_length=150),
        ),
    ]
